project:
  type: website
  output-dir: docs   # <-- GitHub Pages will serve this folder

website:
  title: "My Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: presentation.qmd
        text: Presentation
